### ISSUE TITLE
ricezione del comando di avvio

### ISSUE THREAD

**Issue by andreagarbugli** [andreagarbugli/it.unibo.finaltask#1]
Avviare il robot (già posizionato in A) quando l'utente invia un comando di start. Il robot deve procedere in linea retta ed arrivare ad un punto B.

**Comment by andreagarbugli** [comment]
@lorenzochiarini fare riferimento alla #2

**Comment by lorenzochiarini** [comment]
Alla pressione del pulsante start il robot si avvia procedendo in linea retta. Funzionamento testato nell'ambiente virtuale unity.  Per il momento per l'interazione con l'utente viene usata l'interfaccia web standard.
